travis:
  secure:
    BINSTAR_TOKEN: cRgFeqMjFEHx/0nvZLzDuHa1UCynrshi+xsSLvsEesSR88apfv9j7oS0IR0pvI06Lqbwwg3GlLC20fJ4Rw7Xdja7yJxTMRs4uP3E+Zs21ijYv6a1zNuxxoYgaoIcilCEwOkfb7YPCn3zMMX/7UgPVGADZ3bKudE0wPai9/cncbDe68WydsONjkYEsVJdC5xBP+33udQNACKt1ZijcPdCNF1nD3vV55cwJWLR+wA7DFzUUm5U3tl4Q/m+oGZTPddoa2MBbPv4g7gOjDJuH3GzZvyRo+FfzCDayljTJ76DnwZJ/mc9kjfYc3Rw54mXSk/SSm7bzYT+Mx51qjIL3suym/Sz3ZHXmeuektZWU8ErCQcFH5SmhTmIOm3akX2MZ24SlzjIG1mSjz7e2ZHwaaaJtbZJdbz0hq0LOHkpk84VjgxuZnKJsystfyMJF3/P3FbVUX2a2Z4sJndF9N198UHnSvcpiw2pGmw1IW0wTKq0IPbAXRh/DOe/llizJar3nix190Bj5Nv92hDlwfNoAN+OIVd2WrGAc/mFgHC5wOFcGUJA94hgU0yjXMhf1iacKObzjPGq1DkzCiic8ZJCry3FtDBQfJVl+BkCasyCM0hfQcUebD0dzcg0eJArfIrb44Fpr7lBDJTrQ/LW8bC37dHX3MSy9UmzH9rjSVjMM00KGXo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
